### ISSUE TITLE
Help? it says this when I run the python script.

### ISSUE THREAD

**Issue by Vxlkz** [BUZZARDGTA/GTA-V-Session-Sniffer#17]
Initializing and updating MaxMind's GeoLite2 Country, City and ASN databases ...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\GTA-m\OneDrive\Desktop\GTA-V-Session-Sniffer-main\GTA-V-Session-Sniffer-main\GTA_V_Sess │
│ ion_Sniffer.py:2095 in <module>                                                                  │
│                                                                                                  │
│   2092 cls()                                                                                     │
│   2093 title(f"Initializing and updating MaxMind's GeoLite2 Country, City and ASN databases - {  │
│   2094 print("\nInitializing and updating MaxMind's GeoLite2 Country, City and ASN databases ..  │
│ ❱ 2095 geoip2_enabled, geolite2_asn_reader, geolite2_city_reader, geolite2_country_reader = upd  │
│   2096                                                                                           │
│   2097 cls()                                                                                     │
│   2098 title(f"Initializing MacLookup module - {TITLE}")                                         │
│                                                                                                  │
│ C:\Users\GTA-m\OneDrive\Desktop\GTA-V-Session-Sniffer-main\GTA-V-Session-Sniffer-main\GTA_V_Sess │
│ ion_Sniffer.py:1731 in update_and_initialize_geolite2_readers                                    │
│                                                                                                  │
│   1728 │                                                                                         │
│   1729 │   geolite2_databases_folder_path = Path("GeoLite2 Databases")                           │
│   1730 │                                                                                         │
│ ❱ 1731 │   update_geolite2_databases__dict = update_geolite2_databases()                         │
│   1732 │   exception__initialize_geolite2_readers, geolite2_asn_reader, geolite2_city_reader, g  │
│   1733 │                                                                                         │
│   1734 │   show_error = False                                                                    │
│                                                                                                  │
│ C:\Users\GTA-m\OneDrive\Desktop\GTA-V-Session-Sniffer-main\GTA-V-Session-Sniffer-main\GTA_V_Sess │
│ ion_Sniffer.py:1697 in update_geolite2_databases                                                 │
│                                                                                                  │
│   1694 │   │   │   msgbox_style = MsgBox.Style.OKOnly | MsgBox.Style.Exclamation | MsgBox.Style  │
│   1695 │   │   │   threading.Thread(target=MsgBox.show, args=(msgbox_title, msgbox_message, msg  │
│   1696 │   │                                                                                     │
│ ❱ 1697 │   │   with geolite2_version_file_path.open("w", encoding="utf-8") as f:                 │
│   1698 │   │   │   json.dump({                                                                   │
│   1699 │   │   │   │   name: {"version": info["current_version"]}                                │
│   1700 │   │   │   │   for name, info in geolite2_databases.items()                              │
│                                                                                                  │
│ C:\Users\GTA-m\AppData\Local\Programs\Python\Python313\Lib\pathlib\_local.py:537 in open         │
│                                                                                                  │
│   534 │   │   """                                                                                │
│   535 │   │   if "b" not in mode:                                                                │
│   536 │   │   │   encoding = io.text_encoding(encoding)                                          │
│ ❱ 537 │   │   return io.open(self, mode, buffering, encoding, errors, newline)                   │
│   538 │                                                                                          │
│   539 │   def read_text(self, encoding=None, errors=None, newline=None):                         │
│   540 │   │   """                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'GeoLite2 Databases\\version.json'

An unexpected (uncaught) error occurred. Please kindly report it to:
https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer/issues.

DEBUG:
VERSION=v1.3.0 - 15/12/2024 (16:26)

**Comment by BUZZARDGTA** [comment]
Try running code from main branch and let me know if it has been fixed, I've tried something.
