### ISSUE TITLE
Is a mod menu required for getting usernames?

### ISSUE THREAD

**Issue by LawLess0001** [BUZZARDGTA/GTA-V-Session-Sniffer#18]
title says it all

**Comment by BUZZARDGTA** [comment]
If you want to resolve literally all usernames directly, yes.

https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer?tab=readme-ov-file#about-usernames-decryptionresolving

But you can also manually add them:

https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer/blob/main/docs/SCRIPT_CONFIGURATION.md#userip-ini-databases-configuration

**Comment by LawLess0001** [comment]
If u want to manually add them how would you know someone's ip belongs to that specific person

**Comment by BUZZARDGTA** [comment]
> "If u want to manually add them how would you know someone's ip belongs to that specific person"

https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer/blob/main/docs/TIPS_and_TRICKS.md#obtaining--resolving-someones-ip-address
