### ISSUE TITLE
invalid version help? 

### ISSUE THREAD

**Issue by AI0183** [BUZZARDGTA/GTA-V-Session-Sniffer#20]
Initializing addresses and establishing connection to your PC / Console ...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2411                                                                                 │
│                                                                                                  │
│ in __init__:45                                                                                   │
│                                                                                                  │
│ in get_tshark_path:151                                                                           │
│                                                                                                  │
│ in get_tshark_path:145                                                                           │
│                                                                                                  │
│ in validate_tshark_path:132                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InvalidTSharkVersionException: Invalid TShark version: TShark (Wireshark) 4.2.8 (v4.2.8-0-g91fdcf8e29f8).

An unexpected (uncaught) error occurred. Please kindly report it to:
https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer/issues.

DEBUG:
VERSION=v1.2.9 - 06/12/2024 (13:36)

**Comment by BUZZARDGTA** [comment]
Hello, please install Wireshark version 4.2.9 to fix this issue. I will make it clearer in next version.

**Comment by BUZZARDGTA** [comment]
![WindowsTerminal_2024-12-29_11-24](https://github.com/user-attachments/assets/6494a4ae-5bec-4f98-9338-4fbd67a4f788)

Can't reproduce, make sure you're running last Session Sniffer version

**Comment by BUZZARDGTA** [comment]
Ahhh okay, I managed to reproduce it now, you basically clicked "Ignore" button on this popup and later on the script crashed because of that invalid version. I will be working on a fix now to ignore the invalid tshark version warning and still have the script working.
