### ISSUE TITLE
i dont have an ethernet cable. will ts still work? im also on xbox1

### ISSUE THREAD

**Issue by Vxlkz** [BUZZARDGTA/GTA-V-Session-Sniffer#22]

**Comment by Vxlkz** [comment]
it still says 0 players connected and its on the option that has the same wireless mac and ip address as my console

**Comment by BUZZARDGTA** [comment]
Which game are you playing?

**Comment by BUZZARDGTA** [comment]
As mentioned in your previously opened issues, if you want to scan your Xbox One through your Wi-Fi network, you first need to set up a hotspot on your PC. This will allow you to sniff traffic from your console.

**Comment by Vxlkz** [comment]
> As mentioned in your previously opened issues, if you want to scan your Xbox One through your Wi-Fi network, you first need to set up a hotspot on your PC. This will allow you to sniff traffic from your console.

Ok I’ll try it. Idk how to set one up through my laptop tho

**Comment by BUZZARDGTA** [comment]
watch guides on internet or ask chatgpt idk

**Comment by Vxlkz** [comment]
ok i got the hotspot connected to my console but like theres still no ips being pulled

**Comment by BUZZARDGTA** [comment]
> Which game are you playing?

**Comment by Vxlkz** [comment]
gta v online

**Comment by BUZZARDGTA** [comment]
either you setup your hotspot wrongly or you are not capturing from the right interface

**Comment by Vxlkz** [comment]
how do i find which interface is the correct one?

**Comment by BUZZARDGTA** [comment]
also make sure your Xbox is connected to your created hotspot and not your wifi

**Comment by Vxlkz** [comment]
its connected to my computers hotspot.

**Comment by BUZZARDGTA** [comment]
> how do i find which interface is the correct one?

I can't remember it's either your wifi or it creates a new one, I'm not sure, but I do know some folks using Xbox and my tool, this works.

If you want I can come over your PC and check this out via [AnyDesk](https://anydesk.com/)

**Comment by Vxlkz** [comment]
do u have discord? I can just screenshare if thats ok

**Comment by BUZZARDGTA** [comment]
waitingforharukatoaddme

**Comment by Vxlkz** [comment]
added.
