### ISSUE TITLE
Usernames all showing N/A

### ISSUE THREAD

**Issue by Vxlkz** [BUZZARDGTA/GTA-V-Session-Sniffer#24]
-------------------------------------------------------------------------------------------------------------
Advertising:
  * https://github.com/BUZZARDGTA

Contact Details:
    You can contact me from Email: BUZZARDGTA@protonmail.com, Discord: waitingforharukatoaddme or Telegram: https://t.me/waitingforharukatoaddme

-------------------------------------------------------------------------------------------------------------
                         Welcome in GTA V Session Sniffer v1.2.9 - 06/12/2024 (13:36)
                   This script aims in getting people's address IP from GTA V, WITHOUT MODS.
-   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
                 Scanning on network interface:Ethernet at IP:192.168.137.152 (ARP:Enabled)
            Captured packets average latency per second:0.4/3.0 (tshark restarted time:0) PPS:156
-------------------------------------------------------------------------------------------------------------

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                               Players connected in your session (10):                                                                                │
├────────────┬───────────────┬───────────┬─────────┬────────────┬─────────┬─────┬─────────────────┬───────────┬────────────────────┬──────────────┬─────────────────────────┬────────┬───────┬─────────┤
│ First Seen │ Last Rejoin ↓ │ Usernames │ Rejoins │ T. Packets │ Packets │ PPS │ IP Address      │ Last Port │ Country            │ Region       │ ASN / ISP               │ Mobile │ VPN   │ Hosting │
├────────────┼───────────────┼───────────┼─────────┼────────────┼─────────┼─────┼─────────────────┼───────────┼────────────────────┼──────────────┼─────────────────────────┼────────┼───────┼─────────┤
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 5000       │ 5000    │ 24  │ 68.112.179.61   │ 6672      │ United States (US) │ Wisconsin    │ CHARTER-20115           │ False  │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 2060       │ 2060    │ 27  │ 172.59.121.238  │ 58718     │ United States (US) │ Oklahoma     │ T-MOBILE-AS21928        │ True   │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 7469       │ 7469    │ 38  │ 187.188.23.86   │ 6672      │ Mexico        (MX) │ Veracruz     │ TOTAL PLAY TELECOMUN... │ False  │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 1827       │ 1827    │ 15  │ 216.16.101.8    │ 6672      │ United States (US) │ South Dakota │ CLARITY-TELECOM         │ False  │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 1337       │ 1337    │ 11  │ 98.36.101.70    │ 6672      │ United States (US) │ California   │ COMCAST-7922            │ False  │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 2202       │ 2202    │ 6   │ 177.231.26.164  │ 42736     │ Mexico        (MX) │ Guanajuato   │ Mega Cable, S.A. de ... │ True   │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 2289       │ 2289    │ 11  │ 23.84.217.12    │ 6672      │ United States (US) │ Missouri     │ CHARTER-20115           │ False  │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 724        │ 724     │ 4   │ 76.115.94.153   │ 6672      │ United States (US) │ Oregon       │ COMCAST-7922            │ False  │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 1294       │ 1294    │ 6   │ 73.222.24.253   │ 6672      │ United States (US) │ California   │ COMCAST-7922            │ False  │ False │ False   │
│ 03m 18s    │ 03m 18s       │ N/A       │ 0       │ 2160       │ 2160    │ 14  │ 189.219.210.240 │ 56432     │ Mexico        (MX) │ Nuevo León   │ Television Internaci... │ True   │ False │ False   │
└────────────┴───────────────┴───────────┴─────────┴────────────┴─────────┴─────┴─────────────────┴───────────┴────────────────────┴──────────────┴─────────────────────────┴────────┴───────┴─────────┘
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                             Players who've left your session (2):                                                                              │
├────────────┬─────────────┬─────────────┬───────────┬─────────┬────────────┬─────────┬────────────────┬───────────┬────────────────────┬──────────┬──────────────────┬────────┬───────┬─────────┤
│ First Seen │ Last Rejoin │ Last Seen ↓ │ Usernames │ Rejoins │ T. Packets │ Packets │ IP Address     │ Last Port │ Country            │ Region   │ ASN / ISP        │ Mobile │ VPN   │ Hosting │
├────────────┼─────────────┼─────────────┼───────────┼─────────┼────────────┼─────────┼────────────────┼───────────┼────────────────────┼──────────┼──────────────────┼────────┼───────┼─────────┤
│ 02m 35s    │ 02m 35s     │ 02m 28s     │ N/A       │ 0       │ 44         │ 44      │ 172.58.183.226 │ 38372     │ United States (US) │ Texas    │ T-MOBILE-AS21928 │ True   │ False │ False   │
│ 03m 06s    │ 03m 06s     │ 01m 27s     │ N/A       │ 0       │ 871        │ 871     │ 73.9.38.106    │ 6672      │ United States (US) │ Illinois │ COMCAST-7922     │ False  │ False │ False   │
└────────────┴─────────────┴─────────────┴───────────┴─────────┴────────────┴─────────┴────────────────┴───────────┴────────────────────┴──────────┴──────────────────┴────────┴───────┴─────────┘

Scanning IPs, refreshing display in 3 seconds ...

**Comment by BUZZARDGTA** [comment]
Read this:
https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer?tab=readme-ov-file#about-usernames-decryptionresolving
