### ISSUE TITLE
cached arp issue

### ISSUE THREAD

**Issue by 2jang** [BUZZARDGTA/GTA-V-Session-Sniffer#7]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\123\Downloads\GTA-V-Session-Sniffer\GTA_V_Session_Sniffer.py:2263 in <module>        │
│                                                                                                  │
│   2260 title(f"Capture network interface selection - {TITLE}")                                   │
│   2261 print(f"\nCapture network interface selection ...\n")                                     │
│   2262 if Settings.CAPTURE_ARP:                                                                  │
│ ❱ 2263 │   cached_arp_dict = get_and_parse_arp_cache()                                           │
│   2264                                                                                           │
│   2265 net_io_stats = psutil.net_io_counters(pernic=True)                                        │
│   2266 net_if_addrs = psutil.net_if_addrs()                                                      │
│                                                                                                  │
│ C:\Users\123\Downloads\GTA-V-Session-Sniffer\GTA_V_Session_Sniffer.py:1343 in                 │
│ get_and_parse_arp_cache                                                                          │
│                                                                                                  │
│   1340 │   │   │   ip_address = parts[0]                                                         │
│   1341 │   │   │   mac_address = format_mac_address(parts[1])                                    │
│   1342 │   │   │                                                                                 │
│ ❱ 1343 │   │   │   cached_arp_dict[interface_index]["interface_arp_output"].append(              │
│   1344 │   │   │   │   dict(                                                                     │
│   1345 │   │   │   │   │   ip_address = ip_address,                                              │
│   1346 │   │   │   │   │   mac_address = mac_address                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

Reason: 
In the second conditional, the interface_index should already be included in the cached_arp_dict, but it is proceeding with some interface_indexes missing, which is causing the error.

How I fix: 
```
def get_and_parse_arp_cache():
    def process_arp_output(arp_output: str):
        return arp_output.split(maxsplit=5)

    arp_output = subprocess.check_output(["arp", "-a"], text=True)

    cached_arp_dict: dict[int, dict[str, str | list[Optional[dict[str, str]]]]] = {}

    for parts in map(process_arp_output, arp_output.splitlines()):
        if (
            len(parts) >= 4
            and is_ipv4_address(parts[1])
            and parts[2] == "---"
            and is_hex(parts[3])
        ):
            interface_index = hex_to_int(parts[3])
            interface_info = get_interface_info(interface_index)
            if not interface_info:
                continue

            interface_name: Optional[str] = interface_info.NetConnectionID
            if not isinstance(interface_name, str):
                stdout_crash_text = textwrap.dedent(f"""
                    ERROR:
                        Developer didn't expect this scenario to be possible.

                    INFOS:
                        The "WMI" Python module returned an unexpected
                        type for the interface name; expected 'str'.

                    DEBUG:
                        type(interface_name).__name__: {type(interface_name).__name__}
                        interface_index: {interface_index}
                        interface_name: {interface_name}
                """).removeprefix("\n").removesuffix("\n")
                terminate_script("EXIT", stdout_crash_text, stdout_crash_text)

            interface_ip_address = parts[1]

            # if statement deleted
            cached_arp_dict[interface_index] = dict(
                interface_name=interface_name,
                interface_ip_address=interface_ip_address,
                interface_arp_output=[]
            )
            continue

        if (
            len(parts) >= 3
            and is_ipv4_address(parts[0])
            and is_mac_address(parts[1])
        ):
            ip_address = parts[0]
            mac_address = format_mac_address(parts[1])

            # added
            if interface_index not in cached_arp_dict:
                cached_arp_dict[interface_index] = {
                    "interface_name": "Unknown",
                    "interface_ip_address": "Unknown",
                    "interface_arp_output": []
                }

            cached_arp_dict[interface_index]["interface_arp_output"].append(
                dict(
                    ip_address=ip_address,
                    mac_address=mac_address
                )
            )

    return cached_arp_dict
```

**Comment by BUZZARDGTA** [comment]
Hello, can you send the exact error you get because to me the code you sent should not fix the og issue, as the code should not even be running if `interface_index` is not defined 🤔

**Comment by BUZZARDGTA** [comment]
You can also send the `error.log` file within your sniffer directory.

**Comment by BUZZARDGTA** [comment]
Ans also please send me the output you get after running `ARP -A` in a command prompt.

**Comment by BUZZARDGTA** [comment]
I'm pretty sure I know where the issue is coming from, I will very likely fix it in the next update.

As well as I'm currently re-writting and improving the whole networking part of the script. (network interface selection)

**Comment by 2jang** [comment]
Nice 
and I think it’d be a good idea to split python code into separate files by function.. code was so long

**Comment by BUZZARDGTA** [comment]
In a few minutes I will send you the new arp parser code that will be used if it works for you.

**Comment by BUZZARDGTA** [comment]
Can you try and let me know if it works for you now?

**Comment by 2jang** [comment]
![image](https://github.com/user-attachments/assets/1cc76e55-5279-4f69-bca7-4f8d2445496f)
Yea It's working

**Comment by BUZZARDGTA** [comment]
In the screenshot you send me Session Sniffer, I was expecting you to download the piece of code and run it interdependently like in my screenshot

**Comment by 2jang** [comment]
![image](https://github.com/user-attachments/assets/1f449bc5-0336-4f38-9dff-136cf0910841)
It seems that when I pasted the code into the original script, it worked, but when running it independently, there appears to be an error.

**Comment by BUZZARDGTA** [comment]
mhmm (i've edited the code that's why)

**Comment by BUZZARDGTA** [comment]
thank you for testings

**Comment by 2jang** [comment]
no problem

**Comment by 2jang** [comment]
Will be fixed

**Comment by BUZZARDGTA** [comment]
yes it will be fixed in next update, but i hate it

**Comment by 2jang** [comment]
![image](https://github.com/user-attachments/assets/06dbd5a6-eac3-4150-a023-b5ac7447ac52)
I can give u more info

**Comment by BUZZARDGTA** [comment]
bro it's just windows is shit

**Comment by 2jang** [comment]
import wmi

def print_all_network_adapters():
    c: wmi.WMI = wmi.WMI()

    interfaces = c.Win32_NetworkAdapter()

    for interface in interfaces:
        if interface.NetConnectionID:
            print(f"Interface Name: {interface.NetConnectionID}")
            print(f"Interface Index: {interface.InterfaceIndex}")
            print(f"Description: {interface.Description}")
            print(f"Manufacturer: {interface.Manufacturer}")
            print(f"MAC Address: {interface.MACAddress}")
            print(f"Adapter Type: {interface.AdapterType}")
            print(f"Status: {interface.Status}")
            print(f"Service Name: {interface.ServiceName}")
            print("-" * 40)

print_all_network_adapters()

-----------------------------------------------------------------------------------------------------------------------------------
Interface Name: Wi-Fi
Interface Index: 6
Description: MediaTek Wi-Fi 6 MT7921 Wireless LAN Card
Manufacturer: MediaTek, Inc.
MAC Address: 02:82:7F:58:21:BE
Adapter Type: 이더넷 802.3
Status: None
Service Name: mtkwlex
----------------------------------------
Interface Name: 이더넷
Interface Index: 22
Description: Realtek Gaming GbE Family Controller
Manufacturer: Realtek
MAC Address: 4C:B8:1C:6E:0F:0C
Adapter Type: 이더넷 802.3
Status: None
Service Name: rt640x64
----------------------------------------
Interface Name: Bluetooth 네트워크 연결
Interface Index: 17
Description: Bluetooth Device (Personal Area Network)
Manufacturer: Microsoft
MAC Address: 48:E7:DA:C5:8B:5E
Adapter Type: 이더넷 802.3
Status: None
Service Name: BthPan
----------------------------------------

**Comment by BUZZARDGTA** [comment]
yeah  Interface Index: 42 not showing up ^^

**Comment by BUZZARDGTA** [comment]
Or you can let me know if ARP is working and send me a screenshot of your Network interface selection, look new version:
https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer/releases/tag/v1.2.0

**Comment by 2jang** [comment]
![image](https://github.com/user-attachments/assets/8b8476ff-1f2d-43e0-a10d-ce36e2fbed2e)
new issue

**Comment by 2jang** [comment]
The error indicates that the function Interface.get_interface_by_id(interface_index) returned None, and the code attempted to access the .Name attribute of None, causing an AttributeError.

**Comment by 2jang** [comment]
How i fix : 
#replace this
interface_name = Interface.get_interface_by_id(interface_index).Name

#to this
interface = Interface.get_interface_by_id(interface_index)
if interface is None:
    print(f"Warning: No interface found for index {interface_index}")
    continue
interface_name = interface.Name

**Comment by 2jang** [comment]
![image](https://github.com/user-attachments/assets/c6b976f4-ea39-4381-bc83-5d84feb145f0)
Bro, I’m not sure why the index keeps showing 42 lately, but this seems like an issue we can just handle as an exception and move on.

**Comment by BUZZARDGTA** [comment]
Hello, thanks for testings and letting me know quickly.

The fixed code you sent looks perfect to me.

Do you want to create a pull request so that I accept your changed and you'll become a contributor in the project?

**Comment by 2jang** [comment]
ok l'll create pull request

**Comment by 2jang** [comment]
fixed all arp issue :)
https://github.com/BUZZARDGTA/GTA-V-Session-Sniffer/pull/8
