### ISSUE TITLE
mac_lookup undefined error when change settings.ini

### ISSUE THREAD

**Issue by 2jang** [BUZZARDGTA/GTA-V-Session-Sniffer#9]
![image](https://github.com/user-attachments/assets/19203cd0-f804-47d3-9758-38f948b05d1c)

NameError: name 'mac_lookup' is not defined occurs when change CAPTURE_ARP to False in settings.ini

**Comment by BUZZARDGTA** [comment]
oh that's an optimization I've done to reduce script startup time by removing mac adress resoution cause it seems it was mostly useless.


But now I see why this happens mhmm, I will revert back the behaviour to always resolve mac address

**Comment by BUZZARDGTA** [comment]
thanks, good catching, I can easily fix that.
